version: '3'

services:
  mysql:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ADMIN_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=xpresscart
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    profiles:
      - in_docker
    container_name: xpresscart
    build: .
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=xpresscart
    ports:
      - "3000:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data: