version: '3'

services:
  mysql:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    profiles:
      - in_docker
    container_name: express-docker
    build: .
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=xpresscart
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  db-data:
