name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
    - name: Build docker image
      run: docker build -t integrationninjas



    - name: Install dependencies
      run: npm ci

    - name: Build the application
      run: npm run build --if-present

    - name: Start the application using pm2
      run: pm2 start dist/app.ts
