name: CICD
  
on:
  push:
    branches: [main] 
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
      
      - name: Build and Push Docker Image
        run: |
           docker build -t integrationninjas/nodejs-app .
           docker push integrationninjas/nodejs-app:latest

  
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull integrationninjas/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name nodejs-app-container integrationninjas/nodejs-app
