name: Combined Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set image version (tag)
      id: image_version
      run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/safa-kamal-q/e-commerce-platform:9d3bc24

    - name: Publish docker image
      uses: appleboy/ssh-action@master
      with:
        host: 3.71.188.147
        user: ubuntu
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: deploy
      run: docker compose -f docker-compose-prod.yml up -d
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        GIT_VERSION: ${{ steps.image_version.outputs.gitsha }}
    - name: print logs
      if: always() # This step will be executed even if previous steps fail

      run: docker compose logs

  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "home"
