name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version:  ['14.x', '16.x', '18.x']

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
      
    - name: Set working directory
      run: cd E-commerce-Platform/E-commerce\ Platform


    - name: Install dependencies
      run: npm ci

    - name: Build the application
      run: npm run build --if-present

    - name: Start the application using pm2
      run: pm2 start dist/app.ts
