name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # Hub with the name clockbox.
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $/clockbox:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: docker pull safa-kamal-q/e-commerce-platform:latest

      - name: Delete old container
        run: docker rm -f e-commerce-platform-container

      - name: Run docker container
        run: docker run -d -p 3000:3000 --name e-commerce-platform-container Safa-Kamal-q/E-commerce-Platform
